name: pr validation

on:
  push:
    branches:
      - '*'
      - !main
      - !gh-pages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Installing node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm install

      - run: npm run lint

      - run: npm run build

      - run: npm run export
